### ISSUE TITLE
ScalaJS Support

### ISSUE THREAD

**Issue by matthughes** [circe/circe-fs2#159]
Is there any obvious blocker that prevents this from running in the browser?

**Comment by travisbrown** [comment]
This project relies on Jawn's incremental JSON parsing (called "asynchronous" there, although I don't think that's the clearest name), and Jawn isn't published for Scala.js. I don't think it'd be hard to cross-build Jawn for Scala.js, but I don't personally have any interest in doing (or maintaining) that right now, and I doubt any of the other project owners have the bandwidth. If someone volunteered to be responsible for it I guess it might happen?
