### ISSUE TITLE
"object circe is not a member of package fs2.io"

### ISSUE THREAD

**Issue by sdrafahl** [circe/circe-fs2#183]
Hi I am using scala 2.12.10 and I added you dependency to my SBT file `"io.circe" %% "circe-fs2" % "0.13.0"` but when I try to import `fs2.io._` it just has the above error.

Would you have any idea what the problem might be?

**Comment by sdrafahl** [comment]
nvm, this was a non-issue.

**Comment by kovacshuni** [comment]
Same happens for me. What was your mistake?

**Comment by kovacshuni** [comment]
Solved. Wow, if you import `fs2._` , it won't find `io.circe`. I had to replace with just what I wanted from fs2 (`import fs2.Stream`)

**Comment by BenFradet** [comment]
you can also play with `_root_` imports https://github.com/circe/circe-fs2/blob/master/src/main/scala/io/circe/fs2/ParsingPipe.scala#L3
