### ISSUE TITLE
Cats Effect 3 / fs2 3.x migration

### ISSUE THREAD

**Issue by kubukoz** [circe/circe-fs2#206]
Hi! Are there any plans in place to migrate to Cats Effect 3 / fs2 3.x? If there are any blockers, it would be best to catch them before the RCs are being released. Asking for typelevel/cats-effect#1330 :)

**Comment by BenFradet** [comment]
We'll have to move at some point, yes. I haven't personally looked at migrating yet, however. As a result, I'm not aware of any possible blockers.

**Comment by kubukoz** [comment]
The usage seems pretty simple, I think it'll be straightforward :)

**Comment by kubukoz** [comment]
CE3 is out now 🎉

**Comment by arixmkii** [comment]
Created a PR with a `fs2` bump to 3.0, which transitively includes `cats-effect` 3.0.
