### ISSUE TITLE
Release 0.14.1 with CE3 and FS2 3.x

### ISSUE THREAD

**Issue by valencik** [circe/circe-fs2#259]
With FS2 3.x and CE3 support merged in https://github.com/circe/circe-fs2/issues/206
And the new Circe 0.14.1 bumped https://github.com/circe/circe-fs2/pull/256

Could we get a 0.14.1 release of circe-fs2?

**Comment by travisbrown** [comment]
On its way to Maven Central: https://github.com/circe/circe-fs2/releases/tag/v0.14.0
