### ISSUE TITLE
Sync release version with Circe

### ISSUE THREAD

**Issue by BalmungSan** [circe/circe-fs2#30]
IMHO, it would be convenient if the release version of this is in synchronized with **Circe**. 
Thus, making easier to update all Circe dependencies at the same time. E.g:

```scala
val circeVersion = "0.9.3"                                                                                                                                 
val fs2Version = "0.10.4"
libraryDependencies ++= Seq(                                                                                                  
  "co.fs2" %% "fs2-core" % fs2Version,
  "co.fs2" %% "fs2-io" % fs2Version,
  "io.circe" %% "circe-core" % circeVersion,
  "io.circe" %% "circe-generic" % circeVersion,
  "io.circe" %% "circe-java8" % circeVersion,
  "io.circe" %% "circe-fs2" %  circeVersion // instead of "0.9.0"
)
```

**Note:** Also, you should Bump fs2 to `0.10.4`, Circe to `0.9.3`, Scala to `2.12.6` and SBT to `1.1.5`
_(If you want, I could make that in a PR)._

**Comment by BenFradet** [comment]
>IMHO, it would be convenient if the release version of this is in synchronized with Circe.

The problem would be that it would introduce unnecessary coupling between the two repos, e.g. what happens if there is a bug fix in circe-fs2 that needs releasing?

>Note: Also, you should Bump fs2 to 0.10.4, Circe to 0.9.3, Scala to 2.12.6 and SBT to 1.1.5
(If you want, I could make that in a PR).

yes, please feel free to open a PR with those bumps :+1:

**Comment by travisbrown** [comment]
Yes, thanks, @BalmungSan—a PR with those updates would be much appreciated.

I agree with @BenFradet that the patch versions should be independent (although if there were a _major_ bugfix in a circe patch update we might publish a circe-fs2 artifact for the transitive dependency). It's not ideal, but I think it's worth the cost of having to keep track of an extra version identifier in `build.sbt`.

**Comment by BalmungSan** [comment]
> The problem would be that it would introduce unnecessary coupling between the two repos, e.g. what happens if there is a bug fix in circe-fs2 that needs releasing?

Uhm.. yes I see what you mean, and it is clearly more important than user convenience.

> yes, please feel free to open a PR with those bumps 👍

I've just made it. 👍

**Comment by BalmungSan** [comment]
> but I think it's worth the cost of having to keep track of an extra version identifier in `build.sbt`.

If I understood it well, you mean something like `$circeVersion.$fs2-circePatchVersion`. E.g. `0.9.3.1` ?

**Comment by BalmungSan** [comment]
Anyways it is clear that the release version of this should not be the same of Circe, so for now I'm closing this.
